name: Linux Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"
      - "res/*"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"
      - "res/*"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Purge images from camo.githubusercontent.com
        shell: bash
        run: |
          urls=$(curl -sLk "https://github.com/ziv/raytiles" | grep -Eo "(http|https)://camo.githubusercontent.com[a-zA-Z0-9./?=_%:-]*")
          while IFS= read -r url; do curl -X PURGE "$url"; done <<< "$urls"
        
      - uses: kevincobain2000/action-camo-purge@v1
      

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ninja-build \
            libasound2-dev \
            libx11-dev \
            libxrandr-dev \
            libxi-dev \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            libxcursor-dev \
            libxinerama-dev \
            libwayland-dev \
            libxkbcommon-dev \
            libssl-dev

      - name: Configure CMake
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build Project
        run: cmake --build build --config Release --target Sandbox
