name: macOS Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install LLVM and Ninja
        run: |
          brew update
          brew install llvm ninja

      - name: Configure CMake
        run: |
          export CC=$(brew --prefix llvm)/bin/clang
          export CXX=$(brew --prefix llvm)/bin/clang++
          export SDKROOT=$(xcrun --show-sdk-path)
          
          # יוצר תיקיית build ומשתמש ב-Ninja כדי לקמפל מהר
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build Project
        run: cmake --build build --config Release