name: Windows Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    env:
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg_cache

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Configure CMake
        run: >
          cmake -B build 
          -DCMAKE_BUILD_TYPE=Release 
          -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT\scripts\buildsystems\vcpkg.cmake"

      - name: Build Project
        run: cmake --build build --config Release --target Sandbox