name: Windows Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    env:
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg_cache

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Create Cache Directory
        run: mkdir -p ${{ github.workspace }}/vcpkg_cache

      - name: Cache vcpkg archives
        uses: actions/cache@v5
        with:
          path: ${{ github.workspace }}/vcpkg_cache
          key: vcpkg-openssl-${{ runner.os }}-v2

      - name: Install OpenSSL
        run: vcpkg install openssl:x64-windows

      - name: Configure CMake
        run: >
          cmake -B build 
          -DCMAKE_BUILD_TYPE=Release 
          -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT\scripts\buildsystems\vcpkg.cmake"

      - name: Build Project
        run: cmake --build build --config Release